name: Deploy

on:
  push:
    branches: ['feat/**']

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 15
    
      - name: create env file
        run: |
          touch .env
          echo DEPLOY_PRIVATE_KEY=${{ secrets.DEPLOY_PRIVATE_KEY }} >> .env          
      - run: npm install
      - run: npm run deploy:ropsten
        if: startsWith(github.ref, 'refs/heads/feat')
