name: test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-node@v2
      - run: npm ci
      - run: npm run compile
      - run: npm run test
      - run: npx prettier --list-different ./test/*.js
      - run: npx markdownlint-cli .
      # `npx hardhat check` does not return error code, even if there are `lint errors` reported.
      # Using `grep` to expose error code to `github workflows`
      - run: (! npx hardhat check | grep problem)
