name: Test

on:
  push:
    branches:
      - proposed_change_not_compatible
  pull_request:
    branches:
      - proposed_change_not_compatible

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 15
      - run: npm ci
      - run: npm run compile
      - run: npm run test
      - run: npx prettier --list-different ./test/*.js
